CREATE TABLE IF NOT EXISTS ACCOUNT (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    FOOD DOUBLE,
    MEAL DOUBLE,
    CASH DOUBLE
);

CREATE TABLE IF NOT EXISTS "TRANSACTION" (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    ACCOUNT_ID BIGINT,
    AMOUNT DOUBLE,
    MCC VARCHAR,
    MERCHANT VARCHAR,
    STATUS VARCHAR,
    TRANSACTION_DATE DATE
);

CREATE TABLE IF NOT EXISTS "USER" (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    USERNAME VARCHAR,
    PASSWORD VARCHAR
);